---
# handlers file for nifi

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: >
    ((ansible_distribution == "CentOS"  and
    ansible_distribution_major_version >= "7") or ansible_distribution == "RedHat" or ansible_distribution="Amazon")

- name: restart nifi
  service: name=nifi state=restarted enabled=yes
  when: nifi_perform_restart